#!/bin/bash

grep -q HOST /etc/wwwacct.conf && sed -i_bak "s/\(HOST\) .*/\1 $2/" /etc/wwwacct.conf || echo "HOST $2" >> /etc/wwwacct.conf
/usr/local/cpanel/bin/set_hostname $2

if [ "$1" = "true" ]; then
  /scripts/upcp --force
fi
