#!/bin/bash

FORCESCRIPT = "$1"
HOSTNAME = "$2"

grep -q HOST /etc/wwwacct.conf && sed -i_bak "s/\(HOST\) .*/\1 $HOSTNAME/" /etc/wwwacct.conf || echo "HOST $HOSTNAME" >> /etc/wwwacct.conf

if [ "$FORCESCRIPT" = "true" ]; then
  /scripts/upcp --force
if

